Repository barricklab-at-jhu/Ising_programs, pull requests merged in 2020-06, with the labels that each got.

#3 Develop
  data_conversion/data_conversion_csv/Data_conversion_csv.py
  data_conversion/data_conversion_merge/Data_conversion_merge_CSV.py
  environment.yml
  heteropolymer_fit/Data_conversion_merge_CSV.py
  heteropolymer_fit/Generate_fitting_eqns_heteropolymer.py
  heteropolymer_fit/Ising_fitter_heteropolymer.ipynb
  homopolymer_fit/Data_conversion_Aviv.py
  homopolymer_fit/Generate_fitting_eqns.py
  homopolymer_fit/Ising_fitter_homopolymer.ipynb
  partial_correlation/Partial_correlation.py
  partial_correlation/Partial_correlation_.ipynb
  requirements.txt
Labels: enhancement

#11 Bugfix/remove build info in environments
  README.md
  environment.yml
  requirements.txt
Labels: bug

#12 Bugfix/remove build info in environments
  README.md
  environment.yml
  requirements.txt
Labels: bug

#13 Bugfix/remove build info in environments
  README.md
  environment.yml
  requirements.txt
Labels: bug

#14 Feature/matrixrank
  heteropolymer_fit/generate_fitting_eqns_heteropolymer.py
  heteropolymer_fit/ising_fitter_heteropolymer.ipynb
  homopolymer_fit/generate_fitting_eqns.py
  homopolymer_fit/ising_fitter_homopolymer.ipynb
Labels: enhancement

#10 Feature/add references
  README.md
Labels: documentation

#9 Feature/add references
  README.md
Labels: documentation

#8 Adding references
  README.md
Labels: documentation

#22 Feature/readme bugs
  README.md
  homopolymer_fit/ising_fitter.py
  homopolymer_fit/ising_fitter_parallel.py
Labels: documentation

#21 Feature/readme bugs
  README.md
  homopolymer_fit/ising_fitter.py
  homopolymer_fit/ising_fitter_parallel.py
Labels: documentation

#20 Merge branch 'develop' of https://github.com/barricklab-at-jhu/Ising_…
  README.md
  homopolymer_fit/ising_fitter.py
  homopolymer_fit/ising_fitter_parallel.py
Labels: documentation
